### ISSUE TITLE
TASE seems to have completely blocked the API.

### ISSUE THREAD

**Issue by shlomi-SX** [BenSterenson/pymaya#3]
maya = Maya()

[2022-04-04 16:02:40,466 INFO: response error attempt: 1.0 [in maya_base.py:39]
[2022-04-04 16:02:40,466 INFO: status response code 403, reason Forbidden [in maya_base.py:40]
[2022-04-04 16:02:40,466 INFO: try again in 1 sec... [in maya_base.py:41]
[2022-04-04 16:02:41,468 ERROR: Error in API call [403] - Forbidden [in maya_base.py:54]
[2022-04-04 16:02:41,469 ERROR: Error Bad response to URL: https://api.tase.co.il/api/content/searchentities?lang=1 in GET method [status_code: 403, reason: Forbidden], traceback: Traceback (most recent call last):
  File "/home/kuku/.local/lib/python3.6/site-packages/pymaya/maya_base.py", line 59, in _send_request
    method=response.request.method,
pymaya.exceptions.BadResponseException: Bad response to URL: https://api.tase.co.il/api/content/searchentities?lang=1 in GET method [status_code: 403, reason: Forbidden]
 [in maya_base.py:65]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kuku/.local/lib/python3.6/site-packages/pymaya/maya.py", line 31, in __init__
    self.map_securities()
  File "/home/kuku/.local/lib/python3.6/site-packages/pymaya/maya.py", line 37, in map_securities
    all_securities = self.get_all_securities()
  File "/home/kuku/.local/lib/python3.6/site-packages/pymaya/maya.py", line 34, in get_all_securities
    return self.maya_securities.get_all_securities(lang)
  File "/home/kuku/.local/lib/python3.6/site-packages/cachetools/decorators.py", line 63, in wrapper
    v = method(self, *args, **kwargs)
  File "/home/kuku/.local/lib/python3.6/site-packages/pymaya/maya_security.py", line 18, in get_all_securities
    return self._send_request(MayaAllSecuritiesRequest(lang))
  File "/home/kuku/.local/lib/python3.6/site-packages/cachetools/decorators.py", line 63, in wrapper
    v = method(self, *args, **kwargs)
  File "/home/kuku/.local/lib/python3.6/site-packages/pymaya/maya_base.py", line 59, in _send_request
    method=response.request.method,
pymaya.exceptions.BadResponseException: Bad response to URL: https://api.tase.co.il/api/content/searchentities?lang=1 in GET method [status_code: 403, reason: Forbidden]
>>>

**Comment by BenSterenson** [comment]
should be fixed now

**Comment by shlomifr** [comment]
Thanks Ben,
I tested it, and it works perfectly!
